my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '001001'
      port: 5432
      dbname: parch_and_posey_de # or database instead of dbname
      schema: public
      threads: 1 #[optional, 1 or more]
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      search_path: # optional, override the default postgres search_path